version: "3.9"

services:
  api:
    image: philoupy/auth-server
    ports:
      - "3003:3003"
    deploy:
      mode: global
    environment:
      - DB_URL=https://dgraph.toccatech.com/graphql
      - APP_PORT=3003
      - DOMAIN1=https://toccatech.com
      - DOMAIN2=http://toccatech.fr
      - AUTH_COOKIE=X-Toccatech-Auth
      - JWT_ISS=Toccatech Corporation
      - JWT_SUB=Toccatech Users
      - JWT_AUD=https://toccatech.com
      - JWT_CLAIMS=https://toccatech.com/jwt/claims
      - FILE_SERVER_URL=https://file-server.toccatech.com
